apiVersion: cloudvpn.example.com/v1alpha1
kind: CloudVPN
metadata:
  name: example-cloudvpn
spec:
  vars_file:
    name: cloud-vpn-vars-file
    namespace: myproject
  initiator_ssh_private_key:
    name: cloud-vpn-initiator-ssh-private-key
    namespace: myproject
  responder_ssh_private_key:
    name: cloud-vpn-responder-ssh-private-key
    namespace: myproject
