apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: cloudvpns.cloudvpn.example.com
spec:
  group: cloudvpn.example.com
  names:
    kind: CloudVPN
    listKind: CloudVPNList
    plural: cloudvpns
    singular: cloudvpn
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
