apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvpn-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloudvpn-operator
  template:
    metadata:
      labels:
        name: cloudvpn-operator
    spec:
      serviceAccountName: cloudvpn-operator
      containers:
        - name: cloudvpn-operator
          # Replace this with the built image name
          image: "{{ REPLACE_IMAGE }}"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cloudvpn-operator"
